/*
 * cordic_activation.sv
 * --------------------------------------------------------------------------
 * Multiplier-free (zero-DSP) hardware activation unit computing tanh OR
 * sigmoid on a single shift-add CORDIC datapath.
 *
 *   tanh(z)    = sinh(z)/cosh(z)
 *                Stage A : hyperbolic CORDIC rotation  -> (cosh*K, sinh*K)
 *                Stage B : linear     CORDIC vectoring -> divides y/x (K cancels)
 *   sigmoid(z) = 0.5*(1 + tanh(z/2))   (input pre-shift + output shift/bias)
 *
 * I/O : Q2.12 signed, 14-bit, ready/valid handshake (matches the DSP tanh
 *       baseline this work is compared against).
 * All constants and the iteration schedule come from cordic_consts.svh, which
 * is generated by model/cordic_model.py -- so RTL is bit-exact to the model.
 *
 * Fully pipelined: 1 sample/cycle, latency = 1 + NH_MAX + 1 + ND_MAX + 1.
 * Backpressure: the whole pipeline freezes when i_ready is low (o_ready=i_ready).
 */
`timescale 1ns/1ps
module cordic_activation (
    input  logic              clk,
    input  logic              rst,
    input  logic [13:0]       i_x,      // Q2.12 input
    input  logic              i_mode,   // 0 = tanh, 1 = sigmoid
    input  logic              i_valid,
    output logic              o_ready,
    output logic [13:0]       o_fx,     // Q2.12 output
    output logic              o_valid,
    input  logic              i_ready
);

    `include "cordic_consts.svh"

    wire en = i_ready;
    assign o_ready = i_ready;

    // ---- Stage 0: input register + argument formation ----------------------
    wire signed [WI-1:0] ix_ext = {{(WI-IO_W){i_x[IO_W-1]}}, i_x};

    logic signed [WI-1:0] hx [0:NH_MAX];
    logic signed [WI-1:0] hy [0:NH_MAX];
    logic signed [WI-1:0] hz [0:NH_MAX];
    logic                 hv [0:NH_MAX];
    logic                 hm [0:NH_MAX];

    always_ff @(posedge clk) begin
        if (rst) begin
            hx[0] <= '0; hy[0] <= '0; hz[0] <= '0; hv[0] <= 1'b0; hm[0] <= 1'b0;
        end else if (en) begin
            hx[0] <= X0;                                   // seed x0 = 1.0
            hy[0] <= '0;                                   // seed y0 = 0
            // tanh: z<<(QI-IO_F) ; sigmoid: (z/2)<<(QI-IO_F) = z<<(QI-IO_F-1)
            hz[0] <= i_mode ? (ix_ext <<< (QI-IO_F-1))
                            : (ix_ext <<< (QI-IO_F));
            hv[0] <= i_valid;
            hm[0] <= i_mode;
        end
    end

    // ---- Stage A: hyperbolic CORDIC rotation (NH_MAX shift-add stages) ------
    genvar k;
    generate
        for (k = 0; k < NH_MAX; k++) begin : HYP
            always_ff @(posedge clk) begin
                if (rst) begin
                    hx[k+1] <= '0; hy[k+1] <= '0; hz[k+1] <= '0;
                    hv[k+1] <= 1'b0; hm[k+1] <= 1'b0;
                end else if (en) begin
                    hv[k+1] <= hv[k];
                    hm[k+1] <= hm[k];
                    if (hz[k][WI-1]) begin                 // z < 0  -> d = -1
                        hx[k+1] <= hx[k] - (hy[k] >>> HSHIFT_FLAT[k*SHW +: SHW]);
                        hy[k+1] <= hy[k] - (hx[k] >>> HSHIFT_FLAT[k*SHW +: SHW]);
                        hz[k+1] <= hz[k] + $signed(HATANH_FLAT[k*WI +: WI]);
                    end else begin                         // z >= 0 -> d = +1
                        hx[k+1] <= hx[k] + (hy[k] >>> HSHIFT_FLAT[k*SHW +: SHW]);
                        hy[k+1] <= hy[k] + (hx[k] >>> HSHIFT_FLAT[k*SHW +: SHW]);
                        hz[k+1] <= hz[k] - $signed(HATANH_FLAT[k*WI +: WI]);
                    end
                end
            end
        end
    endgenerate

    // ---- Stage B: linear CORDIC vectoring division  y/x -> tanh ------------
    logic signed [WI-1:0] dx [0:ND_MAX];   // cosh*K, carried constant
    logic signed [WI-1:0] dy [0:ND_MAX];   // sinh*K, driven to 0
    logic signed [WI-1:0] dz [0:ND_MAX];   // accumulates quotient = tanh
    logic                 dv [0:ND_MAX];
    logic                 dm [0:ND_MAX];

    always_ff @(posedge clk) begin          // seed register between the two stages
        if (rst) begin
            dx[0] <= '0; dy[0] <= '0; dz[0] <= '0; dv[0] <= 1'b0; dm[0] <= 1'b0;
        end else if (en) begin
            dx[0] <= hx[NH_MAX];
            dy[0] <= hy[NH_MAX];
            dz[0] <= '0;
            dv[0] <= hv[NH_MAX];
            dm[0] <= hm[NH_MAX];
        end
    end

    genvar j;
    generate
        for (j = 0; j < ND_MAX; j++) begin : DIV
            localparam int SH  = j + 1;                    // shift = 1..ND_MAX
            localparam logic signed [WI-1:0] STEP = (1 << (QI - (j+1)));  // 2^-SH in QI
            always_ff @(posedge clk) begin
                if (rst) begin
                    dx[j+1] <= '0; dy[j+1] <= '0; dz[j+1] <= '0;
                    dv[j+1] <= 1'b0; dm[j+1] <= 1'b0;
                end else if (en) begin
                    dx[j+1] <= dx[j];                      // x stays constant
                    dv[j+1] <= dv[j];
                    dm[j+1] <= dm[j];
                    if (dy[j][WI-1]) begin                 // y < 0  -> d = -1
                        dy[j+1] <= dy[j] + (dx[j] >>> SH);
                        dz[j+1] <= dz[j] - STEP;
                    end else begin                         // y >= 0 -> d = +1
                        dy[j+1] <= dy[j] - (dx[j] >>> SH);
                        dz[j+1] <= dz[j] + STEP;
                    end
                end
            end
        end
    endgenerate

    // ---- Output: sigmoid post-process, round to Q2.12, saturate ------------
    localparam int SHO = QI - IO_F;                        // internal->IO shift
    localparam logic signed [WI-1:0] HALF = (1 << (QI-1));   // 0.5 in QI
    localparam logic signed [WI-1:0] RND  = (1 << (SHO-1));  // round-half-up bias

    wire signed [WI-1:0] post = dm[ND_MAX]
                              ? ((dz[ND_MAX] >>> 1) + HALF)  // sigmoid: 0.5*(1+t)
                              : dz[ND_MAX];
    wire signed [WI-1:0] shifted = (post + RND) >>> SHO;     // round-half-up

    localparam signed [WI-1:0] OUT_MAX =  (1 << (IO_W-1)) - 1;
    localparam signed [WI-1:0] OUT_MIN = -(1 << (IO_W-1));

    always_ff @(posedge clk) begin
        if (rst) begin
            o_fx <= '0; o_valid <= 1'b0;
        end else if (en) begin
            o_valid <= dv[ND_MAX];
            if      (shifted > OUT_MAX) o_fx <= OUT_MAX[IO_W-1:0];
            else if (shifted < OUT_MIN) o_fx <= OUT_MIN[IO_W-1:0];
            else                        o_fx <= shifted[IO_W-1:0];
        end
    end

endmodule
