// AUTO-GENERATED by model/cordic_model.py -- DO NOT EDIT.
// Hyperbolic + linear CORDIC constants (internal QI fixed point).
// NOTE: no include guard on purpose -- these are module-scoped
// localparams and must be re-included inside every module.
// schedule (shift per hyperbolic stage): [1, 2, 3, 4, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 13, 14, 15, 16]

localparam int IO_W = 14;
localparam int IO_F = 12;
localparam int WI   = 22;
localparam int QI   = 16;
localparam int SHW  = 8;  // bits per HSHIFT field
localparam int NH_MAX = 18;   // hyperbolic stages (with repeats)
localparam int ND_MAX = 16; // linear-division stages
localparam logic signed [WI-1:0] X0 = 22'sd65536;

// HSHIFT[k] = HSHIFT_FLAT[k*SHW +: SHW]
localparam logic [143:0] HSHIFT_FLAT = {8'd16, 8'd15, 8'd14, 8'd13, 8'd13, 8'd12, 8'd11, 8'd10, 8'd9, 8'd8, 8'd7, 8'd6, 8'd5, 8'd4, 8'd4, 8'd3, 8'd2, 8'd1};

// HATANH[k] = $signed(HATANH_FLAT[k*WI +: WI])  (all positive)
localparam logic [395:0] HATANH_FLAT = {22'd1, 22'd2, 22'd4, 22'd8, 22'd8, 22'd16, 22'd32, 22'd64, 22'd128, 22'd256, 22'd512, 22'd1024, 22'd2049, 22'd4101, 22'd4101, 22'd8235, 22'd16739, 22'd35999};
